'use client';

import React, { useState } from 'react';
import { Copy, Check, AlertOctagon } from 'lucide-react';
import { toast } from 'sonner';

interface RecommendedPrecautionsProps {
  data: any;
}

export default function RecommendedPrecautions({ data }: RecommendedPrecautionsProps) {
  const [copied, setCopied] = useState(false);

  const precautions = [
    "Do not click any links or download attachments from this message.",
    "Do not reply or attempt to contact the sender using the provided email or phone numbers.",
    "Verify independently: If this claims to be from an organization or bank, visit their official portal directly from your browser.",
    "Report & Purge: Mark this email as Phishing in your email client and permanently remove it from your trash folder."
  ];

  const handleCopySummary = () => {
    const caseId = data?.case_number || 'UNKNOWN';
    const subject = data?.trace?.headers?.Subject || '(No Subject)';
    const sender = data?.trace?.headers?.From || 'Unknown';
    const score = Math.round(data?.assertion?.threat_score || 0);
    const severity = data?.assertion?.severity || (score >= 80 ? 'CRITICAL' : score >= 60 ? 'HIGH' : score >= 40 ? 'MODERATE' : 'LOW');
    const date = data?.created_at ? new Date(data.created_at).toLocaleString() : 'N/A';

    const flags = data?.assertion?.technical_flags || {};
    const property = data?.property || {};
    const lookalikes = data?.assertion?.lookalikes || [];

    const keyFindingsText: string[] = [];
    if (flags.spf_pass === false || flags.dkim_pass === false || flags.dmarc_pass === false) {
      keyFindingsText.push("- Authentication Failure: The sender's email address is forged or spoofed.");
    }
    if (flags.reply_to_mismatch) {
      keyFindingsText.push("- Reply-To Mismatch: Replies are directed to a different address than the sender.");
    }
    if (property?.attachments?.some((a: any) => a.is_suspicious || a.filename?.match(/\.(vbs|exe|bat|cmd|ps1|scr|docm|xlsm)$/i))) {
      keyFindingsText.push("- Dangerous Attachment: Attached file contains executable script commands.");
    }
    if (property?.indicators?.some((i: any) => i.type === 'URL' || i.reputation?.is_flagged) || lookalikes.length > 0) {
      keyFindingsText.push("- Phishing Links: Contains links directing to unverified credential harvesting pages.");
    }
    if (data?.assertion?.is_coordinated_campaign) {
      keyFindingsText.push("- Automated Campaign: Structure matches known automated phishing waves.");
    }
    if (keyFindingsText.length === 0) {
      keyFindingsText.push("- Standard Baseline Verification: No critical threat patterns flagged.");
    }

    const summaryText = `--- AAROHAN THREAT INCIDENT SUMMARY ---
Case ID: ${caseId}
Severity: ${severity} (Threat Score: ${score}/100)
Subject: ${subject}
Sender: ${sender}
Timestamp: ${date}

KEY FINDINGS:
${keyFindingsText.join('\n')}

RECOMMENDED PRECAUTIONS:
${precautions.map(p => `- ${p}`).join('\n')}

Generated by AAROHAN Email Threat Forensics Platform
---------------------------------------`;

    if (navigator.clipboard) {
      navigator.clipboard.writeText(summaryText).then(() => {
        setCopied(true);
        toast.success("Incident summary copied to clipboard for IT ticketing.");
        setTimeout(() => setCopied(false), 2500);
      }).catch((err) => {
        console.error("Clipboard copy failed:", err);
        toast.error("Failed to copy summary to clipboard.");
      });
    }
  };

  return (
    <div className="border border-white/10 bg-white/5 backdrop-blur-md rounded-2xl p-6 shadow-xl space-y-5">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-white/10 pb-4">
        <div className="flex items-center gap-2">
          <div className="p-1.5 bg-cyan-500/10 border border-cyan-500/20 rounded-lg">
            <AlertOctagon className="w-5 h-5 text-cyan-400" />
          </div>
          <div>
            <h3 className="text-[clamp(1rem,2vw,1.25rem)] font-bold tracking-[0.1em] text-slate-100 uppercase">Recommended Precautions</h3>
            <p className="text-xs text-slate-400 font-mono">Immediate safety actions for end-users and analysts</p>
          </div>
        </div>

        <button
          onClick={handleCopySummary}
          className="px-4 py-2 bg-cyan-600/20 hover:bg-cyan-500/30 text-cyan-100 text-xs font-mono font-bold rounded-full transition-all flex items-center gap-2 shadow-[0_0_8px_rgba(56,189,248,0.2)] border border-cyan-500/30 shrink-0"
        >
          {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-cyan-300" />}
          {copied ? "Copied to Clipboard" : "Copy Incident Summary"}
        </button>
      </div>

      <div className="space-y-3">
        {precautions.map((item, idx) => (
          <div key={idx} className="flex items-start gap-3 p-3 bg-white/5 border border-white/10 rounded-xl text-xs text-slate-200 shadow-sm">
            <div className="w-5 h-5 rounded-full bg-amber-500/10 border border-amber-500/30 text-amber-400 flex items-center justify-center text-[10px] font-mono font-bold shrink-0 mt-0.5">
              {idx + 1}
            </div>
            <p className="leading-relaxed text-slate-300">
              {item.startsWith("Verify independently:") ? (
                <>
                  <strong className="text-cyan-300 font-semibold tracking-wide">Verify independently:</strong> {item.replace("Verify independently:", "").trim()}
                </>
              ) : item.startsWith("Report & Purge:") ? (
                <>
                  <strong className="text-rose-300 font-semibold tracking-wide">Report & Purge:</strong> {item.replace("Report & Purge:", "").trim()}
                </>
              ) : (
                item
              )}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}
